name: Deploy app to Production

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-site:
    name: Deploy WebJob
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: telegram-antispam-bot
      
    - name: Build WebJob
      run: dotnet build --no-restore --configuration Release
      working-directory: telegram-antispam-bot
      
    - name: Publish Site
      run: |
        dotnet publish -c Release -o './publish/App_Data/Jobs/Triggered/TelegramAntispamBot' telegram-antispam-bot
      
    - name: 'Deploy Site to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './publish'